#!/usr/bin/env bash

if ! command -v git &> /dev/null
then
	curl -OL https://github.com/santigo-zero/dotfiles/archive/refs/heads/master.zip
	unzip master.zip
	cd dotfiles-master || exit
else
	git clone https://github.com/santigo-zero/dotfiles.git
	cd dotfiles || exit
fi

rsync --verbose \
    --recursive \
    --ignore-times \
    --exclude 'README.md' --exclude "copy-dotfiles" --exclude "clone-dotfiles" --exclude '.git' \
    . "$HOME"

cd "$HOME" || exit
