#!/bin/bash

git clone https://github.com/santigo-zero/dotfiles.git

rsync --verbose \
    --recursive \
    --ignore-times \
    --exclude 'README.md' --exclude "copy-dotfiles" --exclude "restore-dotfiles" --exclude '.git' \
    ./dotfiles "$HOME"

rm -r dotfiles
