#!/usr/bin/env bash

# Git
mkdir -p .config/git
cp -r "$HOME/.config/git/config" .config/git/config

# Autostart
mkdir -p .config/autostart
cp -r "$HOME/.config/autostart/" .config/

# Kitty
mkdir -p .config/kitty
cp -r "$HOME/.config/kitty/kitty.conf" .config/kitty

# Wezterm
mkdir -p .config/wezterm
cp -r "$HOME/.config/wezterm/wezterm.lua" .config/wezterm

# Zsh
cp -r "$HOME/.zshenv" .
cp -r "$HOME/.profile" .
mkdir -p .config/zsh
cp -r "$HOME/.config/zsh/.zshrc" .config/zsh
cp -r "$HOME/.config/zsh/.zlogin" .config/zsh
cp -r "$HOME/.config/zsh/utils.zsh" .config/zsh

# Scripts
mkdir -p .local/bin
cp -r "$HOME/.local/bin/mnt-encrypt-drive" .local/bin
cp -r "$HOME/.local/bin/bcm" .local/bin
cp -r "$HOME/.local/bin/clean-zsh" .local/bin
cp -r "$HOME/.local/bin/pp" .local/bin
cp -r "$HOME/.local/bin/ww" .local/bin
cp -r "$HOME/.local/bin/wwconsole" .local/bin
cp -r "$HOME/.local/bin/wwwebbrowser" .local/bin
cp -r "$HOME/.local/bin/zzz" .local/bin
cp -r "$HOME/.local/bin/drive.py" .local/bin
cp -r "$HOME/.local/bin/_st_kdeconfig.sh" .local/bin
cp -r "$HOME/.local/bin/_st_login.sh" .local/bin
cp -r "$HOME/.local/bin/_st_logout.sh" .local/bin

# Konsole
mkdir -p .local/share/konsole
cp -r "$HOME/.local/share/konsole/host.profile" .local/share/konsole
cp -r "$HOME/.local/share/konsole/main-distrobox.profile" .local/share/konsole

# npm
mkdir -p .config/npm
cp -r "$HOME/.config/npm/npmrc" .config/npm/

# Foo Term
mkdir -p .config/foot
cp -r "$HOME/.config/foot/foot.ini" .config/foot
