FROM quay.io/fedora/fedora-silverblue:41 AS base

COPY files/rpm-ostreed.conf /etc/rpm-ostreed.conf

FROM base AS clean_default_apps

RUN rpm-ostree uninstall --idempotent \
	default-editor \
	firefox \
	firefox-langpacks \
	gnome-classic-session \
	gnome-initial-setup \
	gnome-tour \
	nano-default-editor \
	yelp
FROM clean_default_apps AS install_basic_packages

COPY files/vscode.repo /etc/yum.repos.d/vscode.repo

RUN rpm-ostree install --idempotent \
	brightnessctl \
	clevis \
	clevis-dracut \
	clevis-luks \
	clevis-systemd \
	clevis-udisks2 \
	code \
	ddcutil \
	distrobox \
	dkms \
	efibootmgr \
	git \
	gnome-browser-connector \
	gnome-tweaks \
	hdparm \
	just \
	kernel-devel \
	libgda \
	libgda-sqlite \
	libnotify \
	lm_sensors \
	mesa-vdpau-drivers \
	neovim \
	nvme-cli \
	openssl \
	openssl-devel \
	python3-pyclip \
	sdparm \
	sdparm \
	smartmontools \
	sshfs \
	stow \
	wl-clipboard

FROM install_basic_packages AS final_stage

RUN mkdir -p /etc/systemd/system/multi-user.target.wants && \
	ln -s /usr/lib/systemd/system/rpm-ostreed-automatic.timer /etc/systemd/system/timers.target.wants/

RUN rm -rf /var/* ~/.*
RUN rpm-ostree cleanup -m
RUN ostree container commit
